const mongoose = require("mongoose");

const INVOICE_STATUSES = ["draft", "posted", "open", "partial", "paid", "void"];

const accountingInvoiceSchema = new mongoose.Schema(
  {
    organization: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Organization",
      default: null,
      index: true,
    },
    invoiceNumber: { type: String, required: true, index: true },
    customer: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Customer",
      required: true,
      index: true,
    },
    order: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Order",
      default: null,
      index: true,
    },
    status: {
      type: String,
      enum: INVOICE_STATUSES,
      default: "posted",
      index: true,
    },
    issueDate: { type: Date, required: true, default: Date.now },
    dueDate: { type: Date, required: true },
    currency: { type: String, default: "USD", trim: true, uppercase: true },
    subtotal: { type: Number, default: 0, min: 0 },
    tax: { type: Number, default: 0, min: 0 },
    serviceCharge: { type: Number, default: 0, min: 0 },
    total: { type: Number, required: true, min: 0 },
    amountPaid: { type: Number, default: 0, min: 0 },
    notes: { type: String, default: "", trim: true },
    taxDetails: {
      type: [
        {
          code: { type: String, required: true },
          label: { type: String, default: "" },
          amount: { type: Number, required: true, min: 0 },
        },
      ],
      default: undefined,
    },
    /** The General Ledger entry generated by this invoice */
    journalEntry: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "JournalEntry",
      default: null,
      index: true,
    },
    /** When the invoice was finalized/posted to the GL */
    postedAt: { type: Date, default: null },
    /** User who authorized the posting */
    postedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User", default: null },
  },
  { timestamps: true }
);

const IMMUTABLE_FIELDS = [
  "invoiceNumber",
  "customer",
  "order",
  "total",
  "subtotal",
  "tax",
  "serviceCharge",
  "issueDate",
];

accountingInvoiceSchema.pre("save", function (next) {
  if (this.isNew) return next();

  // "Block edits after posting"
  // If the invoice is already in a state other than 'draft', core fields are immutable.
  if (this.status !== "draft") {
    const modifiedFields = this.modifiedPaths();
    const changedImmutable = modifiedFields.filter((f) =>
      IMMUTABLE_FIELDS.includes(f)
    );

    if (changedImmutable.length > 0) {
      return next(
        new Error(
          `Cannot modify core financial fields (${changedImmutable.join(
            ", "
          )}) on a ${this.status} invoice.`
        )
      );
    }
  }
  next();
});

// Actually, let's keep it simpler as per POS patterns:
// Just transition to 'posted' and ensure NO patch route exists.
// The model-level blocking is a safety net.

accountingInvoiceSchema.index({ customer: 1, status: 1, dueDate: 1 });
accountingInvoiceSchema.index(
  { organization: 1, invoiceNumber: 1 },
  {
    unique: true,
    partialFilterExpression: { organization: { $type: "objectId" } },
  }
);

module.exports = mongoose.model("AccountingInvoice", accountingInvoiceSchema);
module.exports.INVOICE_STATUSES = INVOICE_STATUSES;
