// @ts-nocheck

export default {
  ORGANIZATION_SET: 'ORGANIZATION_SET',
  ORGANIZATIONS_LIST_SET: 'ORGANIZATIONS_LIST_SET',
  SET_ORGANIZATION_SETUP_COMPLETED: 'SET_ORGANIZATION_SETUP_COMPLETED',
  ORGANIZATION_MUTATE_BASE_CURRENCY_ABILITIES: 'ORGANIZATION_MUTATE_BASE_CURRENCY_ABILITIES'
};