"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.STOCKIX_FINANCE_HEALTH_POLL_MS = exports.STOCKIX_FINANCE_HEALTH_TIMEOUT_MS = exports.TENANT_MIGRATION_RETRY_DELAY_MS = exports.TENANT_MIGRATION_MAX_ATTEMPTS = void 0;
exports.TENANT_MIGRATION_MAX_ATTEMPTS = 8;
exports.TENANT_MIGRATION_RETRY_DELAY_MS = 3_000;
exports.STOCKIX_FINANCE_HEALTH_TIMEOUT_MS = 180_000;
exports.STOCKIX_FINANCE_HEALTH_POLL_MS = 2_000;
