export declare const env: {
    readonly DATABASE_URL: string | undefined;
    readonly DB_WAIT_TIMEOUT_MS: number;
    readonly PORT: number;
    readonly PLATFORM_API_SECRET: string | undefined;
    readonly DASHBOARD_URL: string | undefined;
    readonly BOOTSTRAP_ADMIN_EMAIL: string | undefined;
    readonly BOOTSTRAP_ADMIN_PASSWORD: string | undefined;
    readonly ROOT_DOMAIN: string | undefined;
    readonly PUBLIC_BASE_URL_SCHEME: string;
    readonly MAX_TENANT_PORT: number;
    readonly STOCKIX_TENANT_APP_ROOT: string | undefined;
    readonly REPO_ROOT: string | undefined;
    readonly TENANT_ENV_ROOT: string | undefined;
    readonly TRAEFIK_DYNAMIC_DIR: string;
    readonly TRAEFIK_TENANT_UPSTREAM_HOST: string;
    readonly TENANT_INTERNAL_HOST: string;
    readonly CORS_ORIGINS: string | undefined;
    readonly SESSION_SECRET: string | undefined;
    readonly AUTH_TOKEN_SECRET: string | undefined;
    readonly ALLOW_BOOTSTRAP_LOGIN: "0" | "true" | "false" | "1" | undefined;
    readonly PLATFORM_ADMIN_EMAIL: string | undefined;
    readonly PLATFORM_ADMIN_PASSWORD: string | undefined;
    readonly NEXT_PUBLIC_STOCKIX_API_URL: string;
    readonly NEXT_PUBLIC_STOCKIX_PUBLIC_SCHEME: string;
    readonly NEXT_PUBLIC_STOCKIX_ROOT_DOMAIN: string;
    readonly NEXT_PUBLIC_STOCKIX_LOCAL_TENANT_HOST: string;
    readonly SECURITY_HSTS: string;
    readonly SECURITY_X_FRAME_OPTIONS: string;
    readonly SECURITY_REFERRER_POLICY: string;
    readonly SECURITY_X_CONTENT_TYPE_OPTIONS: string;
    readonly SECURITY_CSP_BASE: string;
    readonly STOCKIX_API_URL: string;
    readonly PROVISION_POLL_MS: number;
    readonly PROVISION_MAX_MS: number;
    readonly OWNER_ID: string | undefined;
    readonly PROVISION_ADMIN_EMAIL: string;
    readonly POSTGRES_USER: string | undefined;
    readonly POSTGRES_PASSWORD: string | undefined;
    readonly POSTGRES_DB: string | undefined;
    readonly POSTGRES_HOST_PORT: string | undefined;
    readonly ACME_EMAIL: string | undefined;
    readonly CF_DNS_API_TOKEN: string | undefined;
    readonly STOCKIX_REPO: string | undefined;
    readonly NODE_ENV: string;
    readonly HOSTNAME: string;
    readonly PLAYWRIGHT_TEST_BASE_URL: string | undefined;
    readonly SMOKE_OWNER_ID: string | undefined;
    readonly SIGNUP_DISABLED: "0" | "true" | "false" | "1" | undefined;
    readonly SIGNUP_ALLOWED_DOMAINS: string | undefined;
    readonly SIGNUP_ALLOWED_EMAILS: string | undefined;
    readonly BROWSER_WS_ENDPOINT: string | undefined;
    readonly METRICS_ENDPOINT: string | undefined;
    readonly METRICS_AUTH_TOKEN: string | undefined;
    readonly MONOREPO_VERSION: string | undefined;
    readonly PUBLIC_URL: string | undefined;
    readonly WORKER_SECRET: string;
    readonly WORKER_JOB_ID: string | undefined;
    readonly DB_CLIENT: string | undefined;
    readonly DB_HOST: string | undefined;
    readonly DB_USER: string | undefined;
    readonly DB_PASSWORD: string | undefined;
    readonly DB_CHARSET: string | undefined;
    readonly SYSTEM_DB_CLIENT: string | undefined;
    readonly SYSTEM_DB_HOST: string | undefined;
    readonly SYSTEM_DB_USER: string | undefined;
    readonly SYSTEM_DB_PASSWORD: string | undefined;
    readonly SYSTEM_DB_NAME: string | undefined;
    readonly SYSTEM_DB_CHARSET: string | undefined;
    readonly TENANT_DB_CLIENT: string | undefined;
    readonly TENANT_DB_NAME_PREFIX: string | undefined;
    readonly TENANT_DB_NAME_PERFIX: string | undefined;
    readonly TENANT_DB_HOST: string | undefined;
    readonly TENANT_DB_USER: string | undefined;
    readonly TENANT_DB_PASSWORD: string | undefined;
    readonly TENANT_DB_CHARSET: string | undefined;
    readonly MAIL_HOST: string | undefined;
    readonly MAIL_PORT: string | undefined;
    readonly MAIL_SECURE: "0" | "true" | "false" | "1" | undefined;
    readonly MAIL_USERNAME: string | undefined;
    readonly MAIL_PASSWORD: string | undefined;
    readonly DEPLOYMENT_SECRET_KEY: string | undefined;
    readonly MAIL_FROM_NAME: string | undefined;
    readonly MAIL_FROM_ADDRESS: string | undefined;
    readonly MONGODB_DATABASE_URL: string | undefined;
    readonly AGENDA_DB_COLLECTION: string | undefined;
    readonly AGENDA_POOL_TIME: string | undefined;
    readonly AGENDA_CONCURRENCY: string | undefined;
    readonly AGENDASH_AUTH_USER: string | undefined;
    readonly AGENDASH_AUTH_PASSWORD: string | undefined;
    readonly EASY_SMS_TOKEN: string | undefined;
    readonly JWT_SECRET: string | undefined;
    readonly BASE_URL: string | undefined;
    readonly npm_package_json: string | undefined;
    readonly npm_package_type: string | undefined;
};
export declare const apiConfig: {
    readonly databaseUrl: string;
    readonly platformApiSecret: string;
    readonly workerSecret: string;
    readonly dashboardUrl: string;
    readonly rootDomain: string | undefined;
    readonly corsOrigins: string[];
    readonly port: number;
    readonly publicBaseUrlScheme: string;
    readonly maxTenantPort: number;
    readonly tenantInternalHost: string;
    readonly tenantEnvRoot: string | undefined;
    readonly repoRoot: string | undefined;
    readonly stockixTenantAppRoot: string | undefined;
    readonly traefikDynamicDir: string;
    readonly traefikTenantUpstreamHost: string;
    readonly bootstrapAdminEmail: string | undefined;
    readonly bootstrapAdminPassword: string | undefined;
    readonly nodeEnv: string;
    readonly sessionSecret: string;
    readonly authTokenSecret: string;
    readonly allowBootstrapLogin: boolean;
    readonly hostname: string;
    readonly workerJobId: string | undefined;
    readonly metricsEndpoint: string | undefined;
    readonly metricsAuthToken: string | undefined;
    readonly deploymentSecretKey: string;
    readonly tenantDbNamePrefix: string | undefined;
    readonly validateRequiredEnv: () => void;
};
export declare const dashboardConfig: {
    readonly databaseUrl: string;
    readonly sessionSecret: string;
    readonly platformApiSecret: string;
    readonly platformAdminEmail: string;
    readonly platformAdminPassword: string;
    readonly nodeEnv: string;
    readonly nextPublicApiUrl: string;
    readonly nextPublicScheme: string;
    readonly nextPublicRootDomain: string;
    readonly nextPublicLocalTenantHost: string;
    readonly securityHsts: string;
    readonly securityXFrameOptions: string;
    readonly securityReferrerPolicy: string;
    readonly securityXContentTypeOptions: string;
    readonly securityCspBase: string;
};
export declare const dbConfig: {
    readonly databaseUrl: string;
    readonly waitTimeoutMs: number;
};
export declare const infraConfig: {
    readonly rootDomain: string | undefined;
    readonly nextPublicStockixApiUrl: string;
    readonly postgresUser: string | undefined;
    readonly postgresPassword: string | undefined;
    readonly postgresDb: string | undefined;
    readonly postgresHostPort: string | undefined;
    readonly acmeEmail: string | undefined;
    readonly cloudflareDnsToken: string | undefined;
    readonly stockixRepo: string | undefined;
};
//# sourceMappingURL=index.d.ts.map