export const TENANT_MIGRATION_MAX_ATTEMPTS = 8;
export const TENANT_MIGRATION_RETRY_DELAY_MS = 3_000;
export const STOCKIX_FINANCE_HEALTH_TIMEOUT_MS = 180_000;
export const STOCKIX_FINANCE_HEALTH_POLL_MS = 2_000;
