/**
 * Stockix provision smoke test.
 *
 * Usage (from repo root):
 *   pnpm --filter api exec node scripts/provision-smoke.mjs           # health + owners only
 *   pnpm --filter api exec node scripts/provision-smoke.mjs --full   # POST /tenants + poll (needs Docker, DB, migrations)
 *
 * Env:
 *   STOCKIX_API_URL   default http://localhost:4000
 *   OWNER_ID          optional; otherwise first GET /owners id
 *   PROVISION_POLL_MS default 2000
 *   PROVISION_MAX_MS  default 2700000 (45m)
 *
 * Admin password: NOT chosen by you. The API generates a one-time password server-side,
 * registers BigCapital with POST /api/auth/register, and returns it only in
 * GET /tenants/provision-status/:id while the in-memory job exists (not stored in Postgres).
 */

import { config } from "dotenv";
import path from "node:path";
import { fileURLToPath } from "node:url";

const apiDir = path.join(fileURLToPath(new URL(".", import.meta.url)), "..");
config({ path: path.join(apiDir, ".env") });
config({ path: path.join(apiDir, ".env.local"), override: true });

const API = (process.env.STOCKIX_API_URL ?? "http://localhost:4000").replace(
  /\/$/,
  "",
);
const POLL_MS = Number(process.env.PROVISION_POLL_MS ?? "2000");
const MAX_MS = Number(process.env.PROVISION_MAX_MS ?? String(45 * 60 * 1000));

const full = process.argv.includes("--full");

async function readJson(res) {
  const t = await res.text();
  try {
    return t ? JSON.parse(t) : {};
  } catch {
    return { _raw: t };
  }
}

function fail(msg, extra) {
  console.error("\n❌", msg);
  if (extra != null) console.error(extra);
  console.error(`
Typical fixes:
  • API down → run: pnpm --filter api dev
  • DATABASE_URL wrong / migrations → pnpm --filter @repo/db db:migrate
  • No owner → pnpm --filter @repo/db db:seed:local
  • Docker not running / images → start Docker; first provision pulls images (slow)
  • Port in use / MAX_TENANT_PORT → check env and tenant_deployments.internal_port
  • BigCapital health timeout → see API logs and docker compose logs for the stack
`);
  process.exit(1);
}

async function main() {
  console.log("API:", API, full ? "(full provision)" : "(dry: health + owners only)");

  const h = await fetch(`${API}/health`);
  if (!h.ok) fail(`GET /health → HTTP ${h.status}`, await readJson(h));
  console.log("✓ GET /health", await readJson(h));

  const oRes = await fetch(`${API}/owners`);
  const o = await readJson(oRes);
  if (!oRes.ok) fail(`GET /owners → HTTP ${oRes.status}`, o);

  const owners = o.owners ?? [];
  if (owners.length === 0) {
    fail("No owners in database. Run: pnpm --filter @repo/db db:seed:local");
  }
  console.log("✓ GET /owners count:", owners.length);

  const ownerId = process.env.OWNER_ID ?? owners[0].id;
  console.log("Using owner_id:", ownerId);

  if (!full) {
    console.log(`
Dry run OK. To test full BigCapital provisioning (Docker required):

  pnpm --filter api exec node scripts/provision-smoke.mjs --full

Admin email: you choose it in the JSON body (must match SIGNUP_ALLOWED_EMAILS in the stack).
Admin password: auto-generated by Stockix; printed only in the final status JSON as oneTimeAdminPassword.
`);
    return;
  }

  const slug = `smoke-${Date.now().toString(36)}`;
  const body = {
    slug,
    name: `Smoke test ${slug}`,
    owner_id: ownerId,
    admin_email: process.env.PROVISION_ADMIN_EMAIL ?? "admin-smoke@localhost.test",
    admin_first_name: "Smoke",
    admin_last_name: "Test",
  };

  console.log("POST /tenants", body);
  const pRes = await fetch(`${API}/tenants`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(body),
  });
  const accepted = await readJson(pRes);
  if (pRes.status !== 202 || !accepted.accepted || !accepted.correlationId) {
    fail(`POST /tenants expected 202`, { status: pRes.status, accepted });
  }
  const { correlationId } = accepted;
  console.log("✓ Accepted correlationId:", correlationId);
  console.log("  Poll:", `${API}/tenants/provision-status/${correlationId}`);

  const deadline = Date.now() + MAX_MS;
  while (Date.now() < deadline) {
    await new Promise((r) => setTimeout(r, POLL_MS));
    const sRes = await fetch(`${API}/tenants/provision-status/${correlationId}`);
    const s = await readJson(sRes);
    if (sRes.status === 404) {
      fail("provision-status 404 (API restarted or unknown id)", s);
    }
    if (!sRes.ok) fail(`provision-status HTTP ${sRes.status}`, s);

    if (s.status === "failed") {
      fail("Provisioning failed", {
        error: s.error,
        cause: s.cause,
        lastEvents: s.events?.slice?.(-5),
      });
    }

    if (s.status === "complete") {
      console.log("\n✓ Provisioning complete\n");
      console.log(JSON.stringify(s, null, 2));
      const port = s.internalPort;
      if (port != null) {
        console.log(`
Open in browser (local nginx):
  http://127.0.0.1:${port}

Login:
  Email:    ${body.admin_email}
  Password: ${s.oneTimeAdminPassword ?? "(missing — job may have expired; reprovision or use BC password reset)"}
`);
      }
      return;
    }

    process.stdout.write(
      `. status=${s.status} elapsed=${Math.floor((Date.now() - (deadline - MAX_MS)) / 1000)}s\r`,
    );
  }

  fail(`Timeout after ${MAX_MS}ms — still not complete. Check Docker and API logs.`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
