export {
  DEFAULT_VIEWS,
  DEFAULT_VIEW_COLUMNS,
  ERRORS,
} from '@/constants/Items/constants';

export const ItemsSampleData = [
  {
    'Item Type': 'Inventory',
    'Item Name': 'Hettinger, Schumm and Bartoletti',
    'Item Code': '1000',
    Sellable: 'T',
    Purchasable: 'T',
    'Cost Price': '10000',
    'Sell Price': '1000',
    'Cost Account': 'Cost of Goods Sold',
    'Sell Account': 'Other Income',
    'Inventory Account': 'Inventory Asset',
    'Sell Description': 'Description ....',
    'Purchase Description': 'Description ....',
    Category: 'sdafasdfsadf',
    Note: 'At dolor est non tempore et quisquam.',
    Active: 'TRUE',
  },
  {
    'Item Type': 'Inventory',
    'Item Name': 'Schmitt Group',
    'Item Code': '1001',
    Sellable: 'T',
    Purchasable: 'T',
    'Cost Price': '10000',
    'Sell Price': '1000',
    'Cost Account': 'Cost of Goods Sold',
    'Sell Account': 'Other Income',
    'Inventory Account': 'Inventory Asset',
    'Sell Description': 'Description ....',
    'Purchase Description': 'Description ....',
    Category: 'sdafasdfsadf',
    Note: 'Id perspiciatis at adipisci minus accusamus dolor iure dolore.',
    Active: 'TRUE',
  },
  {
    'Item Type': 'Inventory',
    'Item Name': 'Marks - Carroll',
    'Item Code': '1002',
    Sellable: 'T',
    Purchasable: 'T',
    'Cost Price': '10000',
    'Sell Price': '1000',
    'Cost Account': 'Cost of Goods Sold',
    'Sell Account': 'Other Income',
    'Inventory Account': 'Inventory Asset',
    'Sell Description': 'Description ....',
    'Purchase Description': 'Description ....',
    Category: 'sdafasdfsadf',
    Note: 'Odio odio minus similique.',
    Active: 'TRUE',
  },
  {
    'Item Type': 'Inventory',
    'Item Name': 'VonRueden, Ruecker and Hettinger',
    'Item Code': '1003',
    Sellable: 'T',
    Purchasable: 'T',
    'Cost Price': '10000',
    'Sell Price': '1000',
    'Cost Account': 'Cost of Goods Sold',
    'Sell Account': 'Other Income',
    'Inventory Account': 'Inventory Asset',
    'Sell Description': 'Description ....',
    'Purchase Description': 'Description ....',
    Category: 'sdafasdfsadf',
    Note: 'Quibusdam dolores illo.',
    Active: 'TRUE',
  },
];
